version: '3.8'
services:
  dispatcher:
    image: ghcr.io/ecospherNetwork/agent-nn/dispatcher:latest
    ports:
      - "8000:8000"
    depends_on:
      - registry
      - session_manager

  registry:
    image: ghcr.io/ecospherNetwork/agent-nn/registry:latest
    ports:
      - "8001:8000"

  session_manager:
    image: ghcr.io/ecospherNetwork/agent-nn/session_manager:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "8002:8000"
    depends_on:
      - redis

  vector_store:
    image: ghcr.io/ecospherNetwork/agent-nn/vector_store:latest
    ports:
      - "8003:8000"
    volumes:
      - vector_data:/data

  llm_gateway:
    image: ghcr.io/ecospherNetwork/agent-nn/llm_gateway:latest
    ports:
      - "8004:8000"

  worker_dev:
    image: ghcr.io/ecospherNetwork/agent-nn/worker_dev:latest
    ports:
      - "8010:8000"

  worker_loh:
    image: ghcr.io/ecospherNetwork/agent-nn/worker_loh:latest
    ports:
      - "8011:8000"

  worker_openhands:
    image: ghcr.io/ecospherNetwork/agent-nn/worker_openhands:latest
    ports:
      - "8012:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  vector_data:
