[project]
name = "agentnn"
version = "1.0.0-beta"
description = "Modular agent execution and neural orchestration framework"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
  "fastapi",
  "httpx",
  "typer",
  "pydantic-settings",
  "mlflow"
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[project.scripts]
agentnn = "sdk.cli.main:app"

[project.optional-dependencies]
sdk = []

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
