global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'agent_services'
    static_configs:
      - targets:
          - 'task_dispatcher:8001'
          - 'agent_registry:8002'
          - 'session_manager:8005'
          - 'vector_store:8003'
          - 'llm_gateway:8004'
          - 'api_gateway:8000'
