apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-nn.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "agent-nn.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "agent-nn.name" . }}
    spec:
      containers:
        - name: agent-nn
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: API_GATEWAY_KEY
              value: {{ .Values.gateway.apiKey | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
