version: '3.8'

services:
  dispatcher:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/task_dispatcher/main.py
    ports:
      - "8000:8000"
    depends_on:
      - registry
      - session_manager

  registry:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/agent_registry/main.py
    ports:
      - "8001:8000"

  session_manager:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/session_manager/main.py
    environment:
      - REDIS_HOST=redis
    ports:
      - "8002:8000"
    depends_on:
      - redis

  vector_store:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/vector_store/main.py
    ports:
      - "8003:8000"
    volumes:
      - vector_data:/data

  llm_gateway:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/llm_gateway/main.py
    ports:
      - "8004:8000"

  worker_dev:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/worker_dev/main.py
    ports:
      - "8010:8000"

  worker_loh:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/worker_loh/main.py
    ports:
      - "8011:8000"

  worker_openhands:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python mcp/worker_openhands/main.py
    ports:
      - "8012:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  vector_data:
