llm:
  base_url: "http://192.168.0.247:1234"
  chat_model: "llama-3.2-1b-instruct"
  embedding_model: "text-embedding-nomic-embed-text-v1.5"
  temperature: 0.7
  max_tokens: 2048
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop: null