# Service configuration per environment

default:
  dispatcher:
    port: 8000
    resources:
      cpu: "500m"
      memory: "512Mi"
  agent_registry:
    port: 8001
  session_manager:
    port: 8002
  vector_store:
    port: 8003
  llm_gateway:
    port: 8004
  api_gateway:
    port: 8080

production:
  dispatcher:
    port: 80
    resources:
      cpu: "1"
      memory: "1Gi"
  api_gateway:
    port: 443
