name: Publish Flowise Plugin

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Build plugin
        run: |
          python tools/generate_flowise_plugin.py
          python tools/package_plugin.py --output agentnn_flowise_plugin.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: agentnn_flowise_plugin
          path: agentnn_flowise_plugin.zip
